name: hive_cache
description: Automatically persists and restores states
version: 1.0.1
# repository: https://github.com/my_org/my_repo
topics: [ cache, state-management ]

platforms:
  ? android
  ? ios
  ? linux
  ? macos
  ? web
  ? windows

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  hive_ce: ">=2.10.1 <3.0.0"
  rxdart: ">=0.28.0 <1.0.0"
  synchronized: ">=3.1.1 <4.0.0"

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
